mojaloop/ml-reference-connectors

.circleci/config.yml, .circleci/pipeline.sh
- Refactored publish jobs to publish for all core connectors in the repository
=> ci: refactored publish jobs

airtel-core-connector/src/api-spec/core-connector-api-spec-dfsp.yml, airtel-core-connector/src/domain/CBSClient/types.ts, airtel-core-connector/src/domain/coreConnectorAgg.ts, airtel-core-connector/src/domain/interfaces/types.ts, airtel-core-connector/test/fixtures.ts, airtel-core-connector/test/int/domain/coreConnectorAgg.test.ts
- fix check for pin input from airtel USSD push
- returned data to support testing at POST /send-money
=> chore: prepare core connector for deployment

airtel-core-connector/src/domain/coreConnectorAgg.ts
- return transferId at POST /transfers outbound
=> chore: fix back fxQuotesResponse checks

airtel-core-connector/src/api-spec/core-connector-api-spec-dfsp.yml, airtel-core-connector/src/domain/CBSClient/types.ts, airtel-core-connector/src/domain/coreConnectorAgg.ts
- added more information in airtel send money response
=> chore: returning more information in airtel send money response

airtel-core-connector/src/domain/coreConnectorAgg.ts
- return acceptQuote: true in update transfer phase for payer
=> chore: return acceptQuote: true in update Send Transfer

CODEOWNERS, README.md, airtel-core-connector/package-lock.json, airtel-core-connector/package.json, core-connector-template/.env.example, core-connector-template/docker-compose.yml, core-connector-template/docs/payee-get-parties.md, core-connector-template/docs/payee-quoterequests.md, core-connector-template/docs/payee-transfers.md, core-connector-template/docs/payer-send-money.md, core-connector-template/docs/payer-update-send-money.md, core-connector-template/src/api-spec/core-connector-api-spec-dfsp.yml, core-connector-template/src/core-connector-svc/dfspCoreConnectorRoutes.ts, core-connector-template/src/domain/CBSClient/CBSClient.ts, core-connector-template/src/domain/CBSClient/errors.ts, core-connector-template/src/domain/CBSClient/types.ts, core-connector-template/src/domain/SDKClient/SDKClient.ts, core-connector-template/src/domain/SDKClient/types.ts, core-connector-template/src/domain/coreConnectorAgg.ts, core-connector-template/src/domain/interfaces/errors.ts, core-connector-template/src/domain/interfaces/types.ts, create.sh, docs/CoreConnectorAggregate.md, docs/README.md
- added default sequence diagrams for the core connector template
- added a CODEOWNERS file
=> chore: enhancing core connector template

.circleci/config.yml
=> ci: fix pipeline unit test run

tnm-mw-core-connector/docker-compose.yml, tnm-mw-core-connector/src/config.ts, tnm-mw-core-connector/src/domain/CBSClient/TNMClient.ts, tnm-mw-core-connector/src/domain/CBSClient/types.ts, tnm-mw-core-connector/src/domain/coreConnectorAgg.ts, tnm-mw-core-connector/src/domain/interfaces/types.ts, tnm-mw-core-connector/test/func/docker-compose.yml, tnm-mw-core-connector/test/func/sdk-docker-compose.yml, tnm-mw-core-connector/test/unit/domain/coreConnectorAgg.test.ts
- added collect money function in CBS Client
- fixed failing test cases due to change in Client
=> feat: added collect money function for invoicing customers during send money

airtel-core-connector/src/api-spec/core-connector-api-spec-dfsp.yml, airtel-core-connector/src/core-connector-svc/dfspCoreConnectorRoutes.ts, airtel-core-connector/src/domain/CBSClient/types.ts, airtel-core-connector/src/domain/coreConnectorAgg.ts
Call back functionailty has been implemented. An endpoint has been exposed to expect a call back from airtel. A handleCallback function which checks the transaction status code and performs a refund if any error has occured. If the the refund fails as well, a manual refund has to be implemented.
=> feat: call back functionality

.circleci/config.yml, airtel-core-connector/src/domain/coreConnectorAgg.ts, tnm-mw-core-connector/src/domain/CBSClient/TNMClient.ts, tnm-mw-core-connector/src/domain/CBSClient/types.ts, tnm-mw-core-connector/src/domain/coreConnectorAgg.ts, tnm-mw-core-connector/src/domain/interfaces/types.ts, tnm-mw-core-connector/test/fixtures.ts, tnm-mw-core-connector/test/unit/domain/coreConnectorAgg.test.ts
fix bash based loops in circle ci config
=> ci: fix bash based loops in circle ci config

airtel-core-connector/docs/payer-update-send-money.md, airtel-core-connector/package-lock.json, airtel-core-connector/package.json
- upated sequence diagram for airtel update send money
=> feat: refactored airtel update send money design

.circleci/config.yml, tnm-mw-core-connector/.env.example, tnm-mw-core-connector/src/core-connector-svc/sdkCoreConnectorRoutes.ts, tnm-mw-core-connector/src/domain/CBSClient/TNMClient.ts, tnm-mw-core-connector/src/domain/coreConnectorAgg.ts, tnm-mw-core-connector/test/fixtures.ts, tnm-mw-core-connector/test/int/domain/coreConnectorAgg.test.ts, tnm-mw-core-connector/test/setup.ts, tnm-mw-core-connector/test/unit/domain/coreConnectorAgg.test.ts
- refactoring of the integration test cases
=> chore: implemented changes during integration testing 

airtel-core-connector/package-lock.json, airtel-core-connector/package.json, airtel-core-connector/src/core-connector-svc/dfspCoreConnectorRoutes.ts, airtel-core-connector/src/core-connector-svc/sdkCoreConnectorRoutes.ts, core-connector-template/src/api-spec/core-connector-api-spec-dfsp.yml, tnm-mw-core-connector/package-lock.json, tnm-mw-core-connector/package.json
- added a logger on in catch to print the error
=> chore: added logging at svc catch

tnm-mw-core-connector/src/api-spec/core-connector-api-spec-dfsp.yml
- changed callback endpoint for tnm to post
=> feat: change callback req method to post for tnm

mtn-ug-core-connector/src/domain/coreConnectorAgg.ts
- added middleName to getParties return
=> fix: fixed middleName return in getParties call

.husky/pre-commit, .husky/pre-push, mtn-zm-core-connector/.env.example, mtn-zm-core-connector/src/api-spec/api.oas2.yml, mtn-zm-core-connector/src/api-spec/core-connector-api-spec-dfsp.yml, mtn-zm-core-connector/src/api-spec/core-connector-api-spec-sdk.yml, mtn-zm-core-connector/src/config.ts, mtn-zm-core-connector/src/core-connector-svc/dfspCoreConnectorRoutes.ts, mtn-zm-core-connector/src/domain/CBSClient/types.ts, mtn-zm-core-connector/src/domain/coreConnectorAgg.ts, mtn-zm-core-connector/src/domain/interfaces/errors.ts, mtn-zm-core-connector/src/domain/interfaces/types.ts, mtn-zm-core-connector/test/fixtures.ts, mtn-zm-core-connector/test/int/domain/coreConnectorAgg.test.ts, mtn-zm-core-connector/test/unit/domain/coreConnectorAgg.test.ts
The implementaton of ISO 20022 optional fields that the scheme require was included in the mtn zambia core connector. the api spec  for dsfp was updated to includ payer details such as date of birth . The type was also updated. The extension list functionality in  the core connector aggregate functions were also updated to accomodate the extension list functionlity. Unit tests where then written with assertions to make sure the functinality works
=> feat: implemented mtn zambia kyc data mapping and merchant implementation

mtn-ug-core-connector/src/domain/coreConnectorAgg.ts, mtn-ug-core-connector/test/unit/domain/coreConnectorAgg.test.ts
- refactored kyc checks at quote requests
- returned kyc data at quoterequests
- add kyc data to top level of POST /transfers body
- added checks for Payee KYC data at send-money
=> feat: added kyc checks , respond with kyc data at quoterequests and added kyc data to post transfers. mtnuganda

tnm-mw-core-connector/docs/payer/payer_send_money_update.md, tnm-mw-core-connector/src/domain/coreConnectorAgg.ts, tnm-mw-core-connector/test/unit/domain/coreConnectorAgg.test.ts
- refactored kyc checks at quote requests
- returned kyc data at quoterequests
- add kyc data to top level of POST /transfers body
- added checks for Payee KYC data at send-money
=> feat: added kyc checks , respond with kyc data at quoterequests and added kyc data to post transfers. tnmmalawi

LICENSE.md
=> chore: create license

airtel-zm-core-connector/docs/payer/README.md
- added README.md for airtel send money
=> chore: added send money documentation for airtel

mtn-ug-core-connector/src/api-spec/core-connector-api-spec-dfsp.yml, mtn-ug-core-connector/src/domain/CBSClient/types.ts, mtn-ug-core-connector/src/domain/coreConnectorAgg.ts, mtn-ug-core-connector/test/fixtures.ts, mtn-ug-core-connector/test/unit/domain/coreConnectorAgg.test.ts, zicb-zm-core-connector/package-lock.json
- refactored merchant payment response payloads 
- refactored send money api schema to return sendAmount and sendCurrency
=> fix: fixed merchant payment return payloads for mtn-ug-core-connector

.circleci/config.yml, .husky/commit-msg, .husky/pre-push, package.json
- use prepare script to build before publish
=> ci: use prepare script to build before publish

examples/dfsp/jest.config.js, examples/dfsp/package.json, examples/fxp/jest.config.js, examples/fxp/package.json, src/core-connector-svc/sdkCoreConnectorRoutes.ts
- fixed template eslint config
=> chore: fix response status code at reserve to 200 from 201

examples/dfsp/package.json, examples/dfsp/src/CBSClient.ts, examples/dfsp/test/unit/cbsClient.test.ts, examples/fxp/package.json, src/domain/CBSClient/types.ts, src/domain/dfspCoreConnectorAgg.ts, src/domain/interfaces/types.ts, test/fixtures.ts, test/mocks.ts, test/unit/dfspCoreConnectorAgg.test.ts
- implemented funds unreserve support
=> feat: implemented transfers unreserve

src/core-connector-svc/Service.ts, test/fixtures.ts, test/unit/customServer.test.ts
- added support for a custom server
=> feat: add support for a custom server
